import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loader from "@/components/ui/loader";

const geistSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loader />}>
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-gradient-to-b from-blue-100 to-slate-50 min-h-screen px-5`}
      >
        {children}
      </body>
    </html>
    </Suspense>
  );
}
