import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { AudioTranscriberProvider } from "@/context/AudioTranscriberProvider";


const geistSans = Outfit({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>)
{
  return (
    <html lang="en">
      <AudioTranscriberProvider apiKey={process.env.NEXT_PUBLIC_OPENAI_API_KEY || ""} > 
      
      <body
        className={`${geistSans.className}`}
      >
        {children}
      </body>
      </AudioTranscriberProvider>
    </html>
  );
}
