import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loader from "@/components/ui/loader";

const geistSans = Outfit({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} bg-gradient-to-b from-blue-100 to-slate-100 min-h-screen p-3`}
      >
        {children}
      </body>
    </html>
  );
}
